services:
  npm:
    build:
      context: .
      dockerfile: docker/node/24/Dockerfile
    entrypoint: npm
    volumes:
      - .:/home/ubuntu/app
      - node_modules:/home/ubuntu/app/node_modules
    working_dir: /home/ubuntu/app

  app:
    build:
      context: .
      dockerfile: docker/node/24/Dockerfile
    tty: true
    volumes:
      - .:/home/ubuntu/app
      - node_modules:/home/ubuntu/app/node_modules
    working_dir: /home/ubuntu/app

volumes:
  node_modules:
